name: CI/CD Android App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar ambiente Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Simular build do app
        run: |
          mkdir build
          echo "Este é um ficheiro APK de exemplo" > build/formularioApp.apk

      - name: Fazer testes simulados
        run: echo "Testes simulados com sucesso!"

      - name: Simular deploy
        run: echo "Deploy simulado com sucesso!"

      - name: Guardar APK como artefacto
        uses: actions/upload-artifact@v3
        with:
          name: formularioApp-apk
          path: build/formularioApp.apk
