name: Android CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Instalar JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11

    - name: Configurar permissões Gradle
      run: chmod +x ./gradlew

    - name: Build do projeto
      run: ./gradlew assembleDebug

    - name: Executar testes
      run: ./gradlew test

    - name: Deploy simulado (upload para artefato)
      uses: actions/upload-artifact@v3
      with:
        name: apk-debug
        path: app/build/outputs/apk/debug/app-debug.apk
